decomposer: ['rdd', 'uvd']
preprocessor: "liv"
device: "cuda:5"
chunk_size: 64
views:
  - "front_rgb"
debug: false
max_len: 100

alpha: 1.0

# clean kithen
vec_database_path: "data/vec_databases/clean_kitchen/train"
mode: "ood" # * will override alpha to 0.0
beta: 0.1

# # agibotworld
# vec_database_path: "data/vec_databases/agibotworld_train/train"
# mode: "default"
# beta: 0.25

# # robocerebra
# vec_database_path: "data/vec_databases/robocerebra_train/train"
# mode: "ood" # * will override alpha to 0.0
# beta: 0.25